"""CPU control-flow tests; stock GPU startup remains separately qualified."""
import importlib
import json
import os
import sys
from types import SimpleNamespace

import pytest

from experiments.capture_full_engine_resources import canonical_roster
from experiments import full_engine_bootstrap as bootstrap


def test_roster_preserves_fused_groups_without_duplicate_members():
    census = {"anchor_groups": {"g:model.qkv": ["model.q", "model.k", "model.v"],
                                 "s:model.experts": ["model.experts.0.w1"]},
              "dense_targets": ["model.q", "model.k", "model.v", "model.out"]}
    rows = canonical_roster(census)
    assert [(row["unit_id"], row["module"]) for row in rows] == [
        ("g:model.qkv", "model.qkv"), ("l:model.out", "model.out"),
        ("s:model.experts", "model.experts")]


def test_roster_refuses_ambiguous_modules():
    with pytest.raises(ValueError, match="distinct"):
        canonical_roster({"anchor_groups": {"g:model.x": ["model.a"],
                                            "s:model.x": ["model.b"]}, "dense_targets": []})


@pytest.mark.parametrize("condition", ["absent", "claimed", "forked", "late", "errors"])
def test_worker_cannot_claim_incomplete_or_inherited_bootstrap(monkeypatch, condition):
    recorder = SimpleNamespace(process_id=os.getpid(), _early=True, _errors=[])
    if condition == "forked":
        recorder.process_id += 1
    if condition == "late":
        recorder._early = False
    if condition == "errors":
        recorder._errors.append("fixture history failed")
    monkeypatch.setattr(bootstrap, "_recorder", None if condition == "absent" else recorder)
    monkeypatch.setattr(bootstrap, "_claimed", condition == "claimed")
    with pytest.raises(RuntimeError):
        bootstrap.claim()


def test_worker_claim_is_unique(monkeypatch):
    recorder = SimpleNamespace(process_id=os.getpid(), _early=True, _errors=[])
    plan = {"identity": "fixture"}
    monkeypatch.setattr(bootstrap, "_recorder", recorder)
    monkeypatch.setattr(bootstrap, "_plan", plan)
    monkeypatch.setattr(bootstrap, "_claimed", False)
    assert bootstrap.claim() == (recorder, plan)
    with pytest.raises(RuntimeError):
        bootstrap.claim()


def test_late_bootstrap_fails_before_loading_collector(monkeypatch):
    monkeypatch.setattr(bootstrap, "_recorder", None)
    monkeypatch.setenv("TESSERA_ENGINE_RESOURCE_PLAN", "/unused.json")
    monkeypatch.setitem(sys.modules, "vllm", SimpleNamespace())
    with pytest.raises(RuntimeError, match="precede"):
        bootstrap.start()


@pytest.fixture
def worker_module(monkeypatch):
    class StockWorker:
        def __init__(self, *args, **kwargs):
            self.model_runner = None
        def init_device(self):
            return "device"
        def execute_model(self, scheduler_output):
            return scheduler_output
        def sample_tokens(self, grammar_output):
            return grammar_output
        def initialize_from_config(self, kv_cache_config):
            return "kv initialized"
    monkeypatch.setitem(sys.modules, "vllm.v1.worker.gpu_worker", SimpleNamespace(Worker=StockWorker))
    sys.modules.pop("experiments.full_engine_worker", None)
    module = importlib.import_module("experiments.full_engine_worker")
    yield module
    sys.modules.pop("experiments.full_engine_worker", None)


def test_parameter_classification_keeps_router_and_tied_head_fixed(worker_module):
    classify = worker_module.parameter_category
    units = ["model.layers.2.feed_forward.experts", "model.layers.0.feed_forward.w13"]
    assert classify("model.layers.2.feed_forward.experts.w13_weight", units) == "candidate"
    assert classify("model.layers.2.feed_forward.gate.weight", units) == "fixed"
    assert classify("model.layers.2.feed_forward.experts.routed_experts.e_score_correction_bias", units) == "fixed"
    assert classify("model.layers.2.feed_forward.experts_extra.weight", units) == "fixed"
    assert classify("lm_head.weight", units) == "fixed"
    assert classify("model.embed_tokens.weight", units) == "fixed"


def test_native_observation_hashes_generated_bytes_and_retains_missing_paths(
        monkeypatch, worker_module, tmp_path):
    import hashlib
    from experiments import bench_native_operator
    binary = tmp_path / "cuda_utils.so"
    binary.write_bytes(b"distinct actual generated bytes")
    missing = tmp_path / "deleted.so"
    monkeypatch.setattr(bench_native_operator, "_mapped_shared_libraries", lambda: {binary, missing})
    result = worker_module.native_library_observation()
    assert result["libraries"][str(binary)]["sha256"] == hashlib.sha256(binary.read_bytes()).hexdigest()
    assert result["errors"][0]["path"] == str(missing)
    assert result["runtime_admission"] is False


@pytest.mark.parametrize("library_state", ["absent", "changed"])
def test_invalid_native_owner_identity_retains_raw_capture_and_refusal(
        monkeypatch, worker_module, tmp_path, library_state):
    import hashlib
    import json
    from pathlib import Path
    from experiments.full_engine_resources import analyze_engine_resource_ledger
    source = tmp_path / "native.py"
    source.write_text("# measured native allocation site\n")
    rule = {"schema": "tessera.native_allocation_site_owner_rule.v1",
            "category": "shared", "required_allocation_frames_in_order": [{"name": "allocate"}],
            "required_source_files": {str(source): {"sha256": hashlib.sha256(source.read_bytes()).hexdigest()}},
            "required_mapped_library": {"path": "/fixture/native.so", "sha256": "a" * 64, "bytes": 12}}
    rule_path = tmp_path / "rule.json"
    rule_path.write_text(json.dumps(rule))
    recorder = SimpleNamespace(_errors=[])
    def finish(directory, *, native_ownership_evidence, **kwargs):
        directory.mkdir(parents=True)
        raw = json.loads((Path(__file__).parent / "fixtures/full_engine_resource_ledger.json").read_text())
        raw["native_ownership_evidence"] = native_ownership_evidence
        raw["capture"]["errors"].extend(recorder._errors)
        (directory / "capture.json").write_text(json.dumps(raw))
        return analyze_engine_resource_ledger(raw)
    recorder.finish = finish
    plan = {"output_directory": str(tmp_path / "capture"), "max_invocations_per_unit": 2,
            "native_owner_rule": {"path": str(rule_path), "sha256": hashlib.sha256(rule_path.read_bytes()).hexdigest()}}
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, plan))
    monkeypatch.setattr(worker_module, "full_engine_runtime_observation", lambda plan: {"loaded_package": {}})
    libraries = {} if library_state == "absent" else {"/fixture/native.so": {"sha256": "b" * 64, "bytes": 12}}
    monkeypatch.setattr(worker_module, "native_library_observation", lambda: {"libraries": libraries})
    worker = worker_module.ResourceCaptureWorker()
    worker._resource_armed = True
    worker._resource_owners = lambda: []
    result = worker._resource_write_capture()
    raw = json.loads((Path(result["directory"]) / "capture.json").read_text())
    assert raw["native_ownership_evidence"][0]["mapped_libraries"] == libraries
    assert any("native owner mapped library identity differs" in error for error in raw["capture"]["errors"])
    assert result["receipt"]["status"] == "incomplete"
    assert result["receipt"]["fixed_resources"] is None
    assert any("native owner mapped library identity differs" in error for error in result["receipt"]["issues"])
    assert not result["receipt"]["checkpoints"]


def test_worker_bounds_execute_capture_but_preserves_stock_outputs(monkeypatch, worker_module):
    seen, steps = [], []
    recorder = SimpleNamespace(
        snapshot=lambda label, **kwargs: seen.append(label),
        declare_step_interval=lambda step_id, *, begin, end: steps.append((step_id, begin, end)))
    plan = {"max_execute_calls": 2}
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, plan))
    worker = worker_module.ResourceCaptureWorker()
    assert worker.init_device() == "device"
    worker.resource_capture_arm()
    for index in range(1, 4):
        step = SimpleNamespace(total_num_scheduled_tokens=index, num_scheduled_tokens={"fixture": index},
            scheduled_new_reqs=[], scheduled_cached_reqs=SimpleNamespace(req_ids=[], num_computed_tokens=[]))
        assert worker.execute_model(step) is step
        assert worker.sample_tokens(index) == index
    assert seen == ["device_initialized", "ready_for_workload", "execute:1:begin", "execute:1:end", "sample:1:end",
                    "execute:2:begin", "execute:2:end", "sample:2:end"]
    # The step boundary costs no additional synchronize-and-snapshot: the two
    # checkpoints it names are the ones this worker already took. Declaring
    # them is what turns an observed extent into one the replay can read, and
    # the interval spans the sampler because sampling is per-step work.
    assert steps == [("step:1", "execute:1:begin", "sample:1:end"),
                     ("step:2", "execute:2:begin", "sample:2:end")]
    assert worker._resource_open_step is None
    assert worker._resource_active is False
    # Every armed call is recorded; only the budgeted ones are declared, so a
    # third engine step shows up as the undeclared call a coverage claim names.
    assert [(row["execute_call"], row["declared"]) for row in worker._resource_scheduler_steps] == [
        (1, True), (2, True), (3, False)]
    with pytest.raises(RuntimeError, match="already armed"):
        worker.resource_capture_arm()


def test_zero_token_engine_step_closes_at_its_own_execute_end(monkeypatch, worker_module):
    # The pinned engine core retires a finished request with one more
    # execute_model call that schedules no token and is never sampled
    # (measured: capture a4, execute_call 3, total_num_scheduled_tokens 0, no
    # sample:3:end). A sampler-closed rule alone leaves that step undeclared
    # and coverage partial forever; the step's extent is its execute call.
    seen, steps = [], []
    recorder = SimpleNamespace(
        snapshot=lambda label, **kwargs: seen.append(label),
        declare_step_interval=lambda step_id, *, begin, end: steps.append((step_id, begin, end)))
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, {"max_execute_calls": 3}))
    worker = worker_module.ResourceCaptureWorker()
    worker.init_device()
    worker.resource_capture_arm()
    def step(tokens):
        return SimpleNamespace(total_num_scheduled_tokens=tokens, num_scheduled_tokens={},
            scheduled_new_reqs=[], scheduled_cached_reqs=SimpleNamespace(req_ids=[], num_computed_tokens=[]))
    worker.execute_model(step(512)); worker.sample_tokens(None)
    worker.execute_model(step(1)); worker.sample_tokens(None)
    worker.execute_model(step(0))
    assert steps == [("step:1", "execute:1:begin", "sample:1:end"),
                     ("step:2", "execute:2:begin", "sample:2:end"),
                     ("step:3", "execute:3:begin", "execute:3:end")]
    assert worker._resource_open_step is None
    # A sampled step is never closed early: the execute end of a step that
    # scheduled tokens leaves the step open for its sampler.
    assert seen[-1] == "execute:3:end" and "sample:3:end" not in seen


def test_stock_warmup_cannot_consume_the_workload_capture_budget(monkeypatch, worker_module):
    seen = []
    recorder = SimpleNamespace(snapshot=lambda label, **kwargs: seen.append(label),
                               declare_step_interval=lambda *a, **k: seen.append("step"))
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, {"max_execute_calls": 2}))
    worker = worker_module.ResourceCaptureWorker()
    assert worker.execute_model("stock warmup") == "stock warmup"
    assert worker.sample_tokens("warmup sample") == "warmup sample"
    assert seen == []
    assert worker._resource_calls == 0


def test_first_native_prefix_closes_observer_and_preserves_remaining_stock_execution(monkeypatch, worker_module, tmp_path):
    from contextlib import contextmanager
    checkpoints, finished = [], []
    @contextmanager
    def scope(unit, **kwargs):
        checkpoints.append((unit, "begin"))
        yield
        checkpoints.append((unit, "end"))
    recorder = SimpleNamespace(_errors=[], unit_scope=scope,
                               snapshot=lambda label, **kwargs: checkpoints.append(label),
                               declare_step_interval=lambda *a, **k: pytest.fail(
                                   "a closed prefix declares no step: its execute:N:end "
                                   "and sample:N:end were never snapshotted"))
    roster = [{"unit_id": "g:fixture", "module": "fixture"}]
    plan = {"max_execute_calls": 2, "max_invocations_per_unit": 2,
            "output_directory": str(tmp_path),
            "unit_boundary": "native_apply", "canonical_roster": roster, "observed_units": roster,
            "qualification_prefix": {"native_invocations": 1, "complete_engine_capture": False}}
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, plan))
    worker = worker_module.ResourceCaptureWorker()
    worker._resource_invocations = {"fixture": 0}
    worker._resource_active = worker._resource_armed = True
    monkeypatch.setattr(worker_module, "tensor_leaves", lambda value, name: [])
    def finish(**kwargs):
        finished.append(kwargs)
        return {"receipt": {"status": "incomplete", "fixed_resources": None}}
    worker._resource_write_capture = finish
    boundary = {"unit_id": "g:fixture", "module": "fixture", "boundary": "dense.quant_method.apply", "includes_router": False}
    with worker._resource_observe_apply(boundary, {"arguments": (), "result": None}):
        pass
    assert checkpoints == [("g:fixture", "begin"), ("g:fixture", "end")]
    assert finished == [{"prefix_only": True}]
    assert worker._resource_prefix_closed and not worker._resource_active
    assert "unobserved" in recorder._errors[0]
    step = SimpleNamespace(total_num_scheduled_tokens=1, num_scheduled_tokens={"fixture": 1},
        scheduled_new_reqs=[], scheduled_cached_reqs=SimpleNamespace(req_ids=[], num_computed_tokens=[]))
    assert worker.execute_model(step) is step
    assert worker.sample_tokens("stock result") == "stock result"
    # The call after a closed prefix is still recorded, and recorded as undeclared.
    assert [row["declared"] for row in worker._resource_scheduler_steps] == [False]
    assert worker.resource_capture_finish()["receipt"]["fixed_resources"] is None
    assert len(checkpoints) == 2 and len(finished) == 1
    assert list(tmp_path.glob("prefix-observer-worker-*.pstats"))


@pytest.mark.parametrize("defect", ["two_invocations", "boolean_count", "claims_complete", "partial_roster", "forward_boundary"])
def test_prefix_qualification_refuses_ambiguous_or_full_capture_claims(monkeypatch, worker_module, defect):
    roster = [{"unit_id": "g:fixture", "module": "fixture"}]
    plan = {"unit_boundary": "native_apply", "canonical_roster": roster, "observed_units": roster,
            "qualification_prefix": {"native_invocations": 1, "complete_engine_capture": False}}
    if defect == "two_invocations":
        plan["qualification_prefix"]["native_invocations"] = 2
    elif defect == "boolean_count":
        plan["qualification_prefix"]["native_invocations"] = True
    elif defect == "claims_complete":
        plan["qualification_prefix"]["complete_engine_capture"] = True
    elif defect == "partial_roster":
        plan["observed_units"] = []
    else:
        plan["unit_boundary"] = "module_forward"
    monkeypatch.setattr(worker_module, "claim", lambda: (SimpleNamespace(), plan))
    with pytest.raises(ValueError, match="prefix qualification"):
        worker_module.ResourceCaptureWorker()


def test_failed_stock_execute_still_records_boundary_and_disarms(monkeypatch, worker_module):
    seen, steps = [], []
    recorder = SimpleNamespace(
        snapshot=lambda label, **kwargs: seen.append(label),
        declare_step_interval=lambda step_id, *, begin, end: steps.append(step_id))
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, {"max_execute_calls": 1}))
    def fail(*args):
        raise RuntimeError("stock fixture failed")
    monkeypatch.setattr(worker_module.Worker, "execute_model", fail)
    worker = worker_module.ResourceCaptureWorker()
    worker.resource_capture_arm()
    step = SimpleNamespace(total_num_scheduled_tokens=1, num_scheduled_tokens={"fixture": 1},
        scheduled_new_reqs=[], scheduled_cached_reqs=SimpleNamespace(req_ids=[], num_computed_tokens=[]))
    with pytest.raises(RuntimeError, match="stock fixture"):
        worker.execute_model(step)
    assert seen == ["ready_for_workload", "execute:1:begin", "execute:1:end"]
    # The sampler never ran, so this step is never declared. There is no
    # fallback to execute:1:end: a step ending there would leave the sampler's
    # allocations outside every step, and this step had no sampler at all.
    # Leaving it undeclared drops declared below executed and holds the whole
    # coverage claim open, which is the direction that refuses rather than
    # publishes.
    assert steps == []
    assert worker._resource_open_step == (1, "execute:1:begin")
    assert worker._resource_active is False


def test_worker_preserves_stock_1970_kv_placement_descriptors(monkeypatch, worker_module):
    pytest.importorskip("torch")
    seen = []
    recorder = SimpleNamespace(snapshot=lambda label, **kwargs: seen.append(label))
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, {}))
    worker = worker_module.ResourceCaptureWorker()
    tensor = SimpleNamespace(size=8192, layers=["attention", "recurrent"],
                             layer_stride=512, block_stride=1024, offset=128)
    config = SimpleNamespace(num_blocks=8, kv_cache_tensors=[tensor])
    assert worker.initialize_from_config(config) == "kv initialized"
    assert worker._resource_kv_description["tensors"] == [{
        "size": 8192, "layers": ["attention", "recurrent"],
        "layer_stride": 512, "block_stride": 1024, "offset": 128}]
    assert seen == ["before_kv_allocation", "kv_allocated"]


def test_resolved_kv_description_preserves_group_types_and_capacity_policy(worker_module):
    from dataclasses import dataclass
    torch = pytest.importorskip("torch")

    @dataclass
    class RecurrentSpec:
        block_size: int
        shapes: tuple
        dtypes: tuple
        page_size_padded: int

        @property
        def page_size_bytes(self):
            return self.page_size_padded

    @dataclass
    class Group:
        layer_names: list
        kv_cache_spec: object
        is_eagle_group: bool = False
        enable_kv_transfer: bool = True

    @dataclass
    class Config:
        num_blocks: int
        kv_cache_tensors: list
        kv_cache_groups: list
        prefix_cache_retention_interval: int = 64
        kv_cache_layout: str = "block_layer"

    config = Config(8, [], [Group(["conv"], RecurrentSpec(64, ((2, 4),), (torch.bfloat16,), 1024))])
    cache = SimpleNamespace(gpu_memory_utilization=0.35, kv_cache_memory_bytes=8192,
                            num_gpu_blocks_override=None)
    worker = SimpleNamespace(vllm_config=SimpleNamespace(cache_config=cache),
                             model_runner=SimpleNamespace(kv_cache_config=config, kernel_block_sizes=[64]))
    result = worker_module.kv_configuration_observation(worker, config)
    assert result["capacity_policy"]["values"]["kv_cache_memory_bytes"] == 8192
    assert "block_size" in result["capacity_policy"]["missing_fields"]
    resolved = result["runner_resolved"]
    assert resolved["fields"]["num_blocks"] == 8
    group = resolved["fields"]["kv_cache_groups"][0]
    spec = group["fields"]["kv_cache_spec"]
    assert spec["type"].endswith("RecurrentSpec")
    assert spec["fields"]["dtypes"] == [{"torch_dtype": "torch.bfloat16"}]
    assert result["group_page_size_bytes"] == [1024]
    assert result["physical_backing_bytes"] is None
    assert result["runtime_admission"] is False


def test_kv_config_serialization_refuses_unrecordable_values(worker_module):
    pytest.importorskip("torch")
    with pytest.raises(TypeError, match="unsupported"):
        worker_module.kv_config_value(object())


def test_runtime_owners_retain_aliases_and_host_views_without_traversing_model(
        monkeypatch, worker_module):
    torch = pytest.importorskip("torch")
    buffer = torch.empty(16, dtype=torch.int32)
    state = SimpleNamespace(first=buffer, alias=buffer[1:])
    state.cycle = state
    state.model = torch.nn.Linear(16, 16)
    monkeypatch.setattr(worker_module, "claim", lambda: (None, {}))
    worker = worker_module.ResourceCaptureWorker()
    worker.model_runner = SimpleNamespace(req_states=state)
    owners = list(worker._resource_owners())
    assert {row.owner_id for row in owners} == {"runner:req_states.first", "runner:req_states.alias"}
    assert {row.category for row in owners} == {"shared"}
    assert {row.tensor.untyped_storage().data_ptr() for row in owners} == {buffer.untyped_storage().data_ptr()}


def test_runtime_owner_traversal_is_bounded_and_does_not_call_properties(worker_module):
    pytest.importorskip("torch")
    class State:
        __module__ = "vllm.v1.worker.fixture"

        @property
        def dangerous(self):
            pytest.fail("observer called a property")

    assert list(worker_module.runtime_tensor_leaves(State(), "fixture")) == []
    with pytest.raises(RuntimeError, match="budget"):
        list(worker_module.runtime_tensor_leaves([[[1]]], "fixture", max_nodes=2))


def test_existing_global_workspace_and_retired_cache_buffers_remain_observable(monkeypatch, worker_module):
    torch = pytest.importorskip("torch")
    current, retired = torch.empty(8), torch.empty(4)
    manager = SimpleNamespace(_current_workspaces=[current], _locked=True)
    monkeypatch.setitem(sys.modules, "vllm.v1.worker.workspace", SimpleNamespace(_manager=manager))
    monkeypatch.setitem(sys.modules, "flashinfer.utils", SimpleNamespace(
        _cache_buf={("scratch", torch.device("cpu")): current}, _cache_buf_retired=[retired]))
    rows = [(name, tensor) for root, value in worker_module.persistent_runtime_roots(None)
            for name, tensor in worker_module.runtime_tensor_leaves(value, root)]
    assert len(rows) == 3
    assert sum(tensor is current for _, tensor in rows) == 2
    assert rows[-1][1] is retired


def test_failed_selected_capacity_is_preserved_and_stops_worker(monkeypatch, worker_module, tmp_path):
    import json
    recorder = SimpleNamespace(_errors=[], snapshot=lambda *args, **kwargs: None)
    plan = {"selected_configuration": {"capacity_assertions": {}}, "output_directory": str(tmp_path)}
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, plan))
    observation = {"capacity_assertions": {"passed": False}, "received_argument_scope": "actual initialization argument"}
    monkeypatch.setattr(worker_module, "inspect_worker_kv", lambda *args, **kwargs: observation)
    worker = worker_module.ResourceCaptureWorker()
    worker.model_runner = SimpleNamespace(kv_cache_config=object())
    with pytest.raises(RuntimeError, match="failed selected assertions"):
        worker.initialize_from_config(object())
    assert json.loads(next(tmp_path.glob("kv-worker-*.json")).read_text()) == observation
    assert recorder._errors == ["actual resolved KV capacity differs from selected assertions"]


@pytest.mark.parametrize("defect", ["package_changed", "evidence_changed", "missing_file", "missing_spec", "origin_mismatch"])
def test_full_engine_runtime_preserves_base_and_checks_installed_package(
        monkeypatch, worker_module, tmp_path, defect):
    import copy
    import hashlib
    import json
    from experiments import bench_native_operator
    package = tmp_path / "tessera"
    package.mkdir()
    module_file = package / "__init__.py"
    module_file.write_text("# immutable fixture\n")
    cached_file = package / "cached_unit.py"
    cached_file.write_text("# cache fixture\n")
    cached = SimpleNamespace(__file__=str(cached_file), __spec__=SimpleNamespace(origin=str(cached_file)))
    module = SimpleNamespace(__file__=str(module_file), __spec__=SimpleNamespace(origin=str(module_file)), cached_unit=cached)
    for name in tuple(sys.modules):
        if name == "tessera" or name.startswith("tessera."):
            monkeypatch.delitem(sys.modules, name)
    monkeypatch.setitem(sys.modules, "tessera", module)
    monkeypatch.setitem(sys.modules, "tessera.cached_unit", cached)
    files = {p.name: {"bytes": p.stat().st_size, "sha256": hashlib.sha256(p.read_bytes()).hexdigest()}
             for p in package.iterdir()}
    installer = tmp_path / "installer.json"
    installer.write_text(json.dumps({"plugin_files": files}))
    base = {"schema": "native fixture", "execution": {"native_only": True},
            "source": {"tessera_package_sha256": "a" * 64}}
    monkeypatch.setattr(bench_native_operator, "observe_runtime", lambda image: copy.deepcopy(base))
    plan = {"selected_configuration": {"runtime_image": "fixture@sha256:abc",
            "engine_args": {"enforce_eager": True, "tensor_parallel_size": 1}, "environment": {}},
            "identity": {"configuration_sha256": "b" * 64}, "runtime_evidence": str(installer),
            "runtime_evidence_sha256": hashlib.sha256(installer.read_bytes()).hexdigest(),
            "observer_engine_args": {}, "observer_environment": {}, "scope": "fixture",
            "collector_library_sha256": "c" * 64, "collector_library": "/fixture/collector.so"}
    result = worker_module.full_engine_runtime_observation(plan)
    assert result["base"] == base
    assert result["actual_execution"]["execution_mode"] == "eager"
    assert result["configuration_sha256"] == "b" * 64
    assert result["loaded_package"]["package_files"] == files
    assert result["loaded_package"]["package_files_unchanged_from_installer"] is True
    assert result["loaded_package"]["cached_unit_file"] == str(cached_file)
    timing_plan = dict(plan, observation_mode="timings",
                       blas_workspace_observer={"path": "/fixture/blas.so", "sha256": "d" * 64},
                       native_owner_rule={"path": "/fixture/rule.json", "sha256": "e" * 64})
    timing = worker_module.full_engine_runtime_observation(timing_plan)
    assert timing["instrumentation"] == {"resource_collector": None,
                                         "blas_workspace_observer": None, "native_owner_rule": None}
    resource = worker_module.full_engine_runtime_observation(dict(timing_plan, observation_mode="resources"))
    assert resource["instrumentation"] == {
        "resource_collector": {"library_sha256": "c" * 64, "loaded_path": "/fixture/collector.so"},
        "blas_workspace_observer": {"library_sha256": "d" * 64, "loaded_path": "/fixture/blas.so"},
        "native_owner_rule": timing_plan["native_owner_rule"]}
    if defect == "package_changed":
        cached_file.write_text("# changed after install\n")
        message = "changed from installer"
    elif defect == "evidence_changed":
        installer.write_text(json.dumps({"plugin_files": files, "unplanned_replacement": True}))
        message = "runtime evidence.*digest"
    elif defect == "missing_file":
        cached.__file__ = None
        message = "module.*file/origin"
    elif defect == "missing_spec":
        cached.__spec__ = None
        message = "module.*file/origin"
    elif defect == "origin_mismatch":
        cached.__spec__.origin = str(module_file)
        message = "module.*file/origin"
    with pytest.raises(ValueError, match=message):
        worker_module.full_engine_runtime_observation(plan)


def test_runtime_owners_include_mamba_cpu_gpu_buffer(worker_module, monkeypatch):
    class Tensor:
        pass
    monkeypatch.setitem(sys.modules, "torch", SimpleNamespace(Tensor=Tensor, nn=SimpleNamespace(Module=type("Module", (), {}))))
    # Stock MambaSpecDecodeGPUContext creates this utility wrapper outside
    # vllm.v1.worker.*; both existing backing references must survive census.
    cls = type("CpuGpuBuffer", (), {"__module__": "vllm.v1.utils"})
    buffer = cls()
    buffer.cpu = Tensor()
    buffer.gpu = Tensor()
    assert [name for name, _ in worker_module.runtime_tensor_leaves(buffer, "mamba")] == ["mamba.cpu", "mamba.gpu"]


def test_reference_owner_parameters_include_scales_but_exclude_external_router_alias(worker_module):
    weight, scale, router = object(), object(), object()
    owner = SimpleNamespace(named_parameters=lambda **kwargs: [("weight_fp8", weight), ("bias_alias", router)],
                            named_buffers=lambda **kwargs: [("scale_b", scale)])
    model = SimpleNamespace(named_parameters=lambda **kwargs: [("dense.weight_fp8", weight), ("dense.bias_alias", router),
                                                               ("router.bias", router)],
                            named_buffers=lambda **kwargs: [("dense.scale_b", scale)])
    assert worker_module.reference_candidate_tensor_ids(model, [{"owner": owner, "boundary": "dense.quant_method.apply"}]) == {id(weight), id(scale)}


def test_name_rule_refuses_a_quantized_checkpoint_instead_of_charging_its_scales(worker_module):
    # Regression: the name-based rule names only weight/w13_weight/w2_weight as
    # candidates, so on a quantized checkpoint weight_scale, input_scale and
    # weight_global_scale fall to "fixed" -- a format-sized term charged as a
    # fixed price, which is exactly what disqualifies fixed_resident. The rule
    # stated "source BF16 only" in a comment and enforced it nowhere.
    classify = worker_module.parameter_category
    units = ["model.layers.0.mlp.gate_up_proj"]
    assert classify("model.layers.0.mlp.gate_up_proj.weight_scale", units) == "fixed"
    with pytest.raises(RuntimeError, match="quantized checkpoint"):
        classify("model.layers.0.mlp.gate_up_proj.weight", units, dtype="torch.float8_e4m3fn")
    assert classify("model.layers.0.mlp.gate_up_proj.weight", units, dtype="torch.bfloat16") == "candidate"
    # An unquantized source keeps its previous behaviour exactly.
    assert classify("model.layers.0.mlp.down_proj.weight", units, dtype="torch.bfloat16") == "fixed"


def test_reference_owner_rule_runs_without_a_checkpoint_key_in_the_plan(worker_module):
    # Regression: reference_candidate_tensor_ids used to be gated on
    # plan["reference_checkpoint"] or plan["artifact_checkpoint"], neither of
    # which decides whether the id-based rule is correct. With the boundaries
    # resolved the id rule owns the classification regardless of the plan keys.
    import inspect
    source = inspect.getsource(worker_module.ResourceCaptureWorker._resource_owners)
    assert "reference_checkpoint" not in source
    assert "artifact_checkpoint" not in source
    assert "reference_candidate_tensor_ids(model, self._resource_native_boundaries)" in source


_OBSERVATION_DIGEST = "a" * 64


def _observation_plan(tmp_path, *, receipt=None, rank=0, world_size=2):
    identity = {"schema": "tessera.full_engine_resource_identity.v1",
                "model_sha256": _OBSERVATION_DIGEST, "configuration_sha256": _OBSERVATION_DIGEST,
                "runtime_manifest_sha256": _OBSERVATION_DIGEST,
                "assignment_sha256": _OBSERVATION_DIGEST,
                "canonical_units_sha256": _OBSERVATION_DIGEST,
                "workload_sha256": _OBSERVATION_DIGEST,
                "device_id": 0, "device_uuid": "fixture"}
    if rank is not None:
        identity.update(rank=rank, world_size=world_size)
    plan = {"output_directory": str(tmp_path), "identity": identity}
    if receipt is not None:
        plan["routed_owner_receipt"] = receipt
    return plan


def _observation_worker(worker_module, monkeypatch, plan):
    monkeypatch.setattr(worker_module, "claim", lambda: (SimpleNamespace(), plan))
    return worker_module.ResourceCaptureWorker()


def test_a_plan_with_no_receipt_emits_no_startup_sample_at_all(monkeypatch, worker_module, tmp_path):
    # Nothing to bind ``receipt_resident_bytes`` to means nothing to write: the
    # domain stays open because no sidecar claims it closed.
    worker = _observation_worker(worker_module, monkeypatch, _observation_plan(tmp_path))
    worker._resource_write_startup_sample()
    assert not (tmp_path / "worker-startup.json").exists()


def test_a_startup_sample_without_a_rank_writes_a_named_refusal(monkeypatch, worker_module, tmp_path):
    receipt = {"path": "/fixture/receipt.json", "sha256": _OBSERVATION_DIGEST,
               "schema": "tessera.native_moe_operator_receipt.v1", "resident_bytes": 4096}
    plan = _observation_plan(tmp_path, receipt=receipt, rank=None)
    worker = _observation_worker(worker_module, monkeypatch, plan)
    worker._resource_write_startup_sample()
    payload = json.loads((tmp_path / "worker-startup.json").read_text())
    assert payload["records"] == [] and "no rank/world" in payload["skipped"]
    assert payload["receipt"]["resident_bytes"] == 4096


def test_the_resource_pass_writes_its_own_kv_view_as_the_capacity_witness(
        monkeypatch, worker_module, tmp_path):
    # The intrusive pass's own record is honest about itself: the recorder is
    # attached and has snapshotted, so the projected runtime_admission is False
    # and it can only serve as the witness a read-only pass is compared with.
    worker = _observation_worker(worker_module, monkeypatch, _observation_plan(tmp_path))
    worker._resource_recorder = SimpleNamespace(process_id=os.getpid(), snapshot_count=7)
    worker._resource_kv_description = {
        "num_blocks": 4, "group_page_size_bytes": [1024],
        "resolved_limits": {"max_model_len": 4096, "max_num_seqs": 4,
                            "max_num_batched_tokens": 1024, "tensor_parallel_size": 2},
        "storage": {"storages": [{"device_type": "cuda", "device_id": 0, "address": 4096,
                                  "bytes": 8192, "owners": ["kv_caches[0]"]}],
                    "unique_physical_storage_bytes": 8192, "scope": "fixture"}}
    worker._resource_write_kv_observation(tmp_path)
    record = json.loads((tmp_path / "kv-observation.json").read_text())["records"][0]
    assert record["runtime_admission"] is False
    assert record["admission_evidence"] == {
        "schema": "tessera.full_engine_kv_pass_evidence.v1", "mode": "resources",
        "process_id": os.getpid(), "recorder_attached": True, "snapshot_count": 7,
        "read_only": False,
        "reason": ("intrusive observation pass: the resource recorder is attached and "
                   "synchronized allocator snapshots alter execution, so this record is "
                   "timing- and admission-ineligible")}
    assert (record["rank"], record["world_size"]) == (0, 2)


def test_a_kv_description_without_dedup_backings_writes_a_named_refusal(
        monkeypatch, worker_module, tmp_path):
    worker = _observation_worker(worker_module, monkeypatch, _observation_plan(tmp_path))
    worker._resource_recorder = SimpleNamespace(process_id=os.getpid(), snapshot_count=0)
    worker._resource_kv_description = {"num_blocks": 4}  # no "storage" block
    worker._resource_write_kv_observation(tmp_path)
    payload = json.loads((tmp_path / "kv-observation.json").read_text())
    assert payload["records"] == [] and "no deduplicated" in payload["skipped"]


def test_a_plan_with_no_identity_writes_a_named_refusal_never_a_crash(
        monkeypatch, worker_module, tmp_path):
    # Regression: the emission ran after the ledger was already written, so a
    # bare KeyError here would have failed a capture whose real work succeeded.
    # A missing rank is an observation that was not taken, not a crash.
    worker = _observation_worker(worker_module, monkeypatch, {"output_directory": str(tmp_path)})
    worker._resource_recorder = SimpleNamespace(process_id=os.getpid(), snapshot_count=0)
    worker._resource_kv_description = {
        "num_blocks": 4, "group_page_size_bytes": [1024],
        "resolved_limits": {"max_model_len": 4096, "max_num_seqs": 4,
                            "max_num_batched_tokens": 1024, "tensor_parallel_size": 2},
        "storage": {"storages": [], "unique_physical_storage_bytes": 0, "scope": "fixture"}}
    worker._resource_write_kv_observation(tmp_path)
    payload = json.loads((tmp_path / "kv-observation.json").read_text())
    assert payload["records"] == [] and "no rank/world" in payload["skipped"]


def test_a_receipt_with_no_identity_writes_a_named_refusal_never_a_crash(
        monkeypatch, worker_module, tmp_path):
    receipt = {"path": "/fixture/receipt.json", "sha256": _OBSERVATION_DIGEST,
               "schema": "tessera.native_moe_operator_receipt.v1", "resident_bytes": 4096}
    plan = {"output_directory": str(tmp_path), "routed_owner_receipt": receipt}
    worker = _observation_worker(worker_module, monkeypatch, plan)
    worker._resource_write_startup_sample()
    payload = json.loads((tmp_path / "worker-startup.json").read_text())
    assert payload["records"] == [] and "no rank/world" in payload["skipped"]


def test_a_capture_that_never_initialized_kv_writes_a_named_refusal(
        monkeypatch, worker_module, tmp_path):
    # Regression: a worker whose KV cache was never initialized has no
    # description attribute at all, and reading it eagerly failed a capture
    # whose real work had already been written to disk.
    worker = _observation_worker(worker_module, monkeypatch, _observation_plan(tmp_path))
    worker._resource_recorder = SimpleNamespace(process_id=os.getpid(), snapshot_count=0)
    assert not hasattr(worker, "_resource_kv_description")
    worker._resource_write_kv_observation(tmp_path)
    payload = json.loads((tmp_path / "kv-observation.json").read_text())
    assert payload["records"] == [] and "no deduplicated" in payload["skipped"]
