"""CPU control-flow tests; stock GPU startup remains separately qualified."""
import importlib
import os
import sys
from types import SimpleNamespace

import pytest

from experiments.capture_full_engine_resources import canonical_roster
from experiments import full_engine_bootstrap as bootstrap


def test_roster_preserves_fused_groups_without_duplicate_members():
    census = {"anchor_groups": {"g:model.qkv": ["model.q", "model.k", "model.v"],
                                 "s:model.experts": ["model.experts.0.w1"]},
              "dense_targets": ["model.q", "model.k", "model.v", "model.out"]}
    rows = canonical_roster(census)
    assert [(row["unit_id"], row["module"]) for row in rows] == [
        ("g:model.qkv", "model.qkv"), ("l:model.out", "model.out"),
        ("s:model.experts", "model.experts")]


def test_roster_refuses_ambiguous_modules():
    with pytest.raises(ValueError, match="distinct"):
        canonical_roster({"anchor_groups": {"g:model.x": ["model.a"],
                                            "s:model.x": ["model.b"]}, "dense_targets": []})


@pytest.mark.parametrize("condition", ["absent", "claimed", "forked", "late", "errors"])
def test_worker_cannot_claim_incomplete_or_inherited_bootstrap(monkeypatch, condition):
    recorder = SimpleNamespace(process_id=os.getpid(), _early=True, _errors=[])
    if condition == "forked":
        recorder.process_id += 1
    if condition == "late":
        recorder._early = False
    if condition == "errors":
        recorder._errors.append("fixture history failed")
    monkeypatch.setattr(bootstrap, "_recorder", None if condition == "absent" else recorder)
    monkeypatch.setattr(bootstrap, "_claimed", condition == "claimed")
    with pytest.raises(RuntimeError):
        bootstrap.claim()


def test_worker_claim_is_unique(monkeypatch):
    recorder = SimpleNamespace(process_id=os.getpid(), _early=True, _errors=[])
    plan = {"identity": "fixture"}
    monkeypatch.setattr(bootstrap, "_recorder", recorder)
    monkeypatch.setattr(bootstrap, "_plan", plan)
    monkeypatch.setattr(bootstrap, "_claimed", False)
    assert bootstrap.claim() == (recorder, plan)
    with pytest.raises(RuntimeError):
        bootstrap.claim()


def test_late_bootstrap_fails_before_loading_collector(monkeypatch):
    monkeypatch.setattr(bootstrap, "_recorder", None)
    monkeypatch.setenv("TESSERA_ENGINE_RESOURCE_PLAN", "/unused.json")
    monkeypatch.setitem(sys.modules, "vllm", SimpleNamespace())
    with pytest.raises(RuntimeError, match="precede"):
        bootstrap.start()


@pytest.fixture
def worker_module(monkeypatch):
    class StockWorker:
        def __init__(self, *args, **kwargs):
            self.model_runner = None
        def init_device(self):
            return "device"
        def execute_model(self, scheduler_output):
            return scheduler_output
        def sample_tokens(self, grammar_output):
            return grammar_output
        def initialize_from_config(self, kv_cache_config):
            return "kv initialized"
    monkeypatch.setitem(sys.modules, "vllm.v1.worker.gpu_worker", SimpleNamespace(Worker=StockWorker))
    sys.modules.pop("experiments.full_engine_worker", None)
    module = importlib.import_module("experiments.full_engine_worker")
    yield module
    sys.modules.pop("experiments.full_engine_worker", None)


def test_parameter_classification_keeps_router_and_tied_head_fixed(worker_module):
    classify = worker_module.parameter_category
    units = ["model.layers.2.feed_forward.experts", "model.layers.0.feed_forward.w13"]
    assert classify("model.layers.2.feed_forward.experts.w13_weight", units) == "candidate"
    assert classify("model.layers.2.feed_forward.gate.weight", units) == "fixed"
    assert classify("model.layers.2.feed_forward.experts.routed_experts.e_score_correction_bias", units) == "fixed"
    assert classify("model.layers.2.feed_forward.experts_extra.weight", units) == "fixed"
    assert classify("lm_head.weight", units) == "fixed"
    assert classify("model.embed_tokens.weight", units) == "fixed"


def test_native_observation_hashes_generated_bytes_and_retains_missing_paths(
        monkeypatch, worker_module, tmp_path):
    import hashlib
    from experiments import bench_native_operator
    binary = tmp_path / "cuda_utils.so"
    binary.write_bytes(b"distinct actual generated bytes")
    missing = tmp_path / "deleted.so"
    monkeypatch.setattr(bench_native_operator, "_mapped_shared_libraries", lambda: {binary, missing})
    result = worker_module.native_library_observation()
    assert result["libraries"][str(binary)]["sha256"] == hashlib.sha256(binary.read_bytes()).hexdigest()
    assert result["errors"][0]["path"] == str(missing)
    assert result["runtime_admission"] is False


def test_worker_bounds_execute_capture_but_preserves_stock_outputs(monkeypatch, worker_module):
    seen = []
    recorder = SimpleNamespace(snapshot=lambda label, **kwargs: seen.append(label))
    plan = {"max_execute_calls": 2}
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, plan))
    worker = worker_module.ResourceCaptureWorker()
    assert worker.init_device() == "device"
    worker.resource_capture_arm()
    for index in range(1, 4):
        step = SimpleNamespace(total_num_scheduled_tokens=index, num_scheduled_tokens={"fixture": index},
            scheduled_new_reqs=[], scheduled_cached_reqs=SimpleNamespace(req_ids=[], num_computed_tokens=[]))
        assert worker.execute_model(step) is step
        assert worker.sample_tokens(index) == index
    assert seen == ["device_initialized", "ready_for_workload", "execute:1:begin", "execute:1:end", "sample:1:end",
                    "execute:2:begin", "execute:2:end", "sample:2:end"]
    assert worker._resource_active is False
    assert len(worker._resource_scheduler_steps) == 2
    with pytest.raises(RuntimeError, match="already armed"):
        worker.resource_capture_arm()


def test_stock_warmup_cannot_consume_the_workload_capture_budget(monkeypatch, worker_module):
    seen = []
    recorder = SimpleNamespace(snapshot=lambda label, **kwargs: seen.append(label))
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, {"max_execute_calls": 2}))
    worker = worker_module.ResourceCaptureWorker()
    assert worker.execute_model("stock warmup") == "stock warmup"
    assert worker.sample_tokens("warmup sample") == "warmup sample"
    assert seen == []
    assert worker._resource_calls == 0


def test_failed_stock_execute_still_records_boundary_and_disarms(monkeypatch, worker_module):
    seen = []
    recorder = SimpleNamespace(snapshot=lambda label, **kwargs: seen.append(label))
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, {"max_execute_calls": 1}))
    def fail(*args):
        raise RuntimeError("stock fixture failed")
    monkeypatch.setattr(worker_module.Worker, "execute_model", fail)
    worker = worker_module.ResourceCaptureWorker()
    worker.resource_capture_arm()
    step = SimpleNamespace(total_num_scheduled_tokens=1, num_scheduled_tokens={"fixture": 1},
        scheduled_new_reqs=[], scheduled_cached_reqs=SimpleNamespace(req_ids=[], num_computed_tokens=[]))
    with pytest.raises(RuntimeError, match="stock fixture"):
        worker.execute_model(step)
    assert seen == ["ready_for_workload", "execute:1:begin", "execute:1:end"]
    assert worker._resource_active is False


def test_worker_preserves_stock_1970_kv_placement_descriptors(monkeypatch, worker_module):
    seen = []
    recorder = SimpleNamespace(snapshot=lambda label, **kwargs: seen.append(label))
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, {}))
    worker = worker_module.ResourceCaptureWorker()
    tensor = SimpleNamespace(size=8192, layers=["attention", "recurrent"],
                             layer_stride=512, block_stride=1024, offset=128)
    config = SimpleNamespace(num_blocks=8, kv_cache_tensors=[tensor])
    assert worker.initialize_from_config(config) == "kv initialized"
    assert worker._resource_kv_description["tensors"] == [{
        "size": 8192, "layers": ["attention", "recurrent"],
        "layer_stride": 512, "block_stride": 1024, "offset": 128}]
    assert seen == ["before_kv_allocation", "kv_allocated"]


def test_resolved_kv_description_preserves_group_types_and_capacity_policy(worker_module):
    from dataclasses import dataclass
    import torch

    @dataclass
    class RecurrentSpec:
        block_size: int
        shapes: tuple
        dtypes: tuple
        page_size_padded: int

        @property
        def page_size_bytes(self):
            return self.page_size_padded

    @dataclass
    class Group:
        layer_names: list
        kv_cache_spec: object
        is_eagle_group: bool = False
        enable_kv_transfer: bool = True

    @dataclass
    class Config:
        num_blocks: int
        kv_cache_tensors: list
        kv_cache_groups: list
        prefix_cache_retention_interval: int = 64
        kv_cache_layout: str = "block_layer"

    config = Config(8, [], [Group(["conv"], RecurrentSpec(64, ((2, 4),), (torch.bfloat16,), 1024))])
    cache = SimpleNamespace(gpu_memory_utilization=0.35, kv_cache_memory_bytes=8192,
                            num_gpu_blocks_override=None)
    worker = SimpleNamespace(vllm_config=SimpleNamespace(cache_config=cache),
                             model_runner=SimpleNamespace(kv_cache_config=config, kernel_block_sizes=[64]))
    result = worker_module.kv_configuration_observation(worker, config)
    assert result["capacity_policy"]["values"]["kv_cache_memory_bytes"] == 8192
    assert "block_size" in result["capacity_policy"]["missing_fields"]
    resolved = result["runner_resolved"]
    assert resolved["fields"]["num_blocks"] == 8
    group = resolved["fields"]["kv_cache_groups"][0]
    spec = group["fields"]["kv_cache_spec"]
    assert spec["type"].endswith("RecurrentSpec")
    assert spec["fields"]["dtypes"] == [{"torch_dtype": "torch.bfloat16"}]
    assert result["group_page_size_bytes"] == [1024]
    assert result["physical_backing_bytes"] is None
    assert result["runtime_admission"] is False


def test_kv_config_serialization_refuses_unrecordable_values(worker_module):
    with pytest.raises(TypeError, match="unsupported"):
        worker_module.kv_config_value(object())


def test_runtime_owners_retain_aliases_and_host_views_without_traversing_model(
        monkeypatch, worker_module):
    import torch
    buffer = torch.empty(16, dtype=torch.int32)
    state = SimpleNamespace(first=buffer, alias=buffer[1:])
    state.cycle = state
    state.model = torch.nn.Linear(16, 16)
    monkeypatch.setattr(worker_module, "claim", lambda: (None, {}))
    worker = worker_module.ResourceCaptureWorker()
    worker.model_runner = SimpleNamespace(req_states=state)
    owners = list(worker._resource_owners())
    assert {row.owner_id for row in owners} == {"runner:req_states.first", "runner:req_states.alias"}
    assert {row.category for row in owners} == {"shared"}
    assert {row.tensor.untyped_storage().data_ptr() for row in owners} == {buffer.untyped_storage().data_ptr()}


def test_runtime_owner_traversal_is_bounded_and_does_not_call_properties(worker_module):
    class State:
        __module__ = "vllm.v1.worker.fixture"

        @property
        def dangerous(self):
            pytest.fail("observer called a property")

    assert list(worker_module.runtime_tensor_leaves(State(), "fixture")) == []
    with pytest.raises(RuntimeError, match="budget"):
        list(worker_module.runtime_tensor_leaves([[[1]]], "fixture", max_nodes=2))


def test_existing_global_workspace_and_retired_cache_buffers_remain_observable(monkeypatch, worker_module):
    import torch
    current, retired = torch.empty(8), torch.empty(4)
    manager = SimpleNamespace(_current_workspaces=[current], _locked=True)
    monkeypatch.setitem(sys.modules, "vllm.v1.worker.workspace", SimpleNamespace(_manager=manager))
    monkeypatch.setitem(sys.modules, "flashinfer.utils", SimpleNamespace(
        _cache_buf={("scratch", torch.device("cpu")): current}, _cache_buf_retired=[retired]))
    rows = [(name, tensor) for root, value in worker_module.persistent_runtime_roots(None)
            for name, tensor in worker_module.runtime_tensor_leaves(value, root)]
    assert len(rows) == 3
    assert sum(tensor is current for _, tensor in rows) == 2
    assert rows[-1][1] is retired


def test_failed_selected_capacity_is_preserved_and_stops_worker(monkeypatch, worker_module, tmp_path):
    import json
    recorder = SimpleNamespace(_errors=[], snapshot=lambda *args, **kwargs: None)
    plan = {"selected_configuration": {"capacity_assertions": {}}, "output_directory": str(tmp_path)}
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, plan))
    observation = {"capacity_assertions": {"passed": False}, "received_argument_scope": "actual initialization argument"}
    monkeypatch.setattr(worker_module, "inspect_worker_kv", lambda *args, **kwargs: observation)
    worker = worker_module.ResourceCaptureWorker()
    worker.model_runner = SimpleNamespace(kv_cache_config=object())
    with pytest.raises(RuntimeError, match="failed selected assertions"):
        worker.initialize_from_config(object())
    assert json.loads(next(tmp_path.glob("kv-worker-*.json")).read_text()) == observation
    assert recorder._errors == ["actual resolved KV capacity differs from selected assertions"]


@pytest.mark.parametrize("defect", ["package_changed", "evidence_changed", "missing_file", "missing_spec", "origin_mismatch"])
def test_full_engine_runtime_preserves_base_and_checks_installed_package(
        monkeypatch, worker_module, tmp_path, defect):
    import copy
    import hashlib
    import json
    from experiments import bench_native_operator
    package = tmp_path / "tessera"
    package.mkdir()
    module_file = package / "__init__.py"
    module_file.write_text("# immutable fixture\n")
    cached_file = package / "cached_unit.py"
    cached_file.write_text("# cache fixture\n")
    cached = SimpleNamespace(__file__=str(cached_file), __spec__=SimpleNamespace(origin=str(cached_file)))
    module = SimpleNamespace(__file__=str(module_file), __spec__=SimpleNamespace(origin=str(module_file)), cached_unit=cached)
    for name in tuple(sys.modules):
        if name == "tessera" or name.startswith("tessera."):
            monkeypatch.delitem(sys.modules, name)
    monkeypatch.setitem(sys.modules, "tessera", module)
    monkeypatch.setitem(sys.modules, "tessera.cached_unit", cached)
    files = {p.name: {"bytes": p.stat().st_size, "sha256": hashlib.sha256(p.read_bytes()).hexdigest()}
             for p in package.iterdir()}
    installer = tmp_path / "installer.json"
    installer.write_text(json.dumps({"plugin_files": files}))
    base = {"schema": "native fixture", "execution": {"native_only": True},
            "source": {"tessera_package_sha256": "a" * 64}}
    monkeypatch.setattr(bench_native_operator, "observe_runtime", lambda image: copy.deepcopy(base))
    plan = {"selected_configuration": {"runtime_image": "fixture@sha256:abc",
            "engine_args": {"enforce_eager": True, "tensor_parallel_size": 1}, "environment": {}},
            "identity": {"configuration_sha256": "b" * 64}, "runtime_evidence": str(installer),
            "runtime_evidence_sha256": hashlib.sha256(installer.read_bytes()).hexdigest(),
            "observer_engine_args": {}, "observer_environment": {}, "scope": "fixture",
            "collector_library_sha256": "c" * 64, "collector_library": "/fixture/collector.so"}
    result = worker_module.full_engine_runtime_observation(plan)
    assert result["base"] == base
    assert result["actual_execution"]["execution_mode"] == "eager"
    assert result["configuration_sha256"] == "b" * 64
    assert result["loaded_package"]["package_files"] == files
    assert result["loaded_package"]["package_files_unchanged_from_installer"] is True
    assert result["loaded_package"]["cached_unit_file"] == str(cached_file)
    timing_plan = dict(plan, observation_mode="timings",
                       blas_workspace_observer={"path": "/fixture/blas.so", "sha256": "d" * 64},
                       native_owner_rule={"path": "/fixture/rule.json", "sha256": "e" * 64})
    timing = worker_module.full_engine_runtime_observation(timing_plan)
    assert timing["instrumentation"] == {"resource_collector": None,
                                         "blas_workspace_observer": None, "native_owner_rule": None}
    resource = worker_module.full_engine_runtime_observation(dict(timing_plan, observation_mode="resources"))
    assert resource["instrumentation"] == {
        "resource_collector": {"library_sha256": "c" * 64, "loaded_path": "/fixture/collector.so"},
        "blas_workspace_observer": {"library_sha256": "d" * 64, "loaded_path": "/fixture/blas.so"},
        "native_owner_rule": timing_plan["native_owner_rule"]}
    if defect == "package_changed":
        cached_file.write_text("# changed after install\n")
        message = "changed from installer"
    elif defect == "evidence_changed":
        installer.write_text(json.dumps({"plugin_files": files, "unplanned_replacement": True}))
        message = "runtime evidence.*digest"
    elif defect == "missing_file":
        cached.__file__ = None
        message = "module.*file/origin"
    elif defect == "missing_spec":
        cached.__spec__ = None
        message = "module.*file/origin"
    elif defect == "origin_mismatch":
        cached.__spec__.origin = str(module_file)
        message = "module.*file/origin"
    with pytest.raises(ValueError, match=message):
        worker_module.full_engine_runtime_observation(plan)


def test_runtime_owners_include_mamba_cpu_gpu_buffer(worker_module, monkeypatch):
    class Tensor:
        pass
    monkeypatch.setitem(sys.modules, "torch", SimpleNamespace(Tensor=Tensor, nn=SimpleNamespace(Module=type("Module", (), {}))))
    # Stock MambaSpecDecodeGPUContext creates this utility wrapper outside
    # vllm.v1.worker.*; both existing backing references must survive census.
    cls = type("CpuGpuBuffer", (), {"__module__": "vllm.v1.utils"})
    buffer = cls()
    buffer.cpu = Tensor()
    buffer.gpu = Tensor()
    assert [name for name, _ in worker_module.runtime_tensor_leaves(buffer, "mamba")] == ["mamba.cpu", "mamba.gpu"]


def test_reference_owner_parameters_include_scales_but_exclude_external_router_alias(worker_module):
    weight, scale, router = object(), object(), object()
    owner = SimpleNamespace(named_parameters=lambda **kwargs: [("weight_fp8", weight), ("bias_alias", router)],
                            named_buffers=lambda **kwargs: [("scale_b", scale)])
    model = SimpleNamespace(named_parameters=lambda **kwargs: [("dense.weight_fp8", weight), ("dense.bias_alias", router),
                                                               ("router.bias", router)],
                            named_buffers=lambda **kwargs: [("dense.scale_b", scale)])
    assert worker_module.reference_candidate_tensor_ids(model, [{"owner": owner, "boundary": "dense.quant_method.apply"}]) == {id(weight), id(scale)}
