"""CPU control-flow tests; stock GPU startup remains separately qualified."""
import importlib
import os
import sys
from types import SimpleNamespace

import pytest

from experiments.capture_full_engine_resources import canonical_roster
from experiments import full_engine_bootstrap as bootstrap


def test_roster_preserves_fused_groups_without_duplicate_members():
    census = {"anchor_groups": {"g:model.qkv": ["model.q", "model.k", "model.v"],
                                 "s:model.experts": ["model.experts.0.w1"]},
              "dense_targets": ["model.q", "model.k", "model.v", "model.out"]}
    rows = canonical_roster(census)
    assert [(row["unit_id"], row["module"]) for row in rows] == [
        ("g:model.qkv", "model.qkv"), ("l:model.out", "model.out"),
        ("s:model.experts", "model.experts")]


def test_roster_refuses_ambiguous_modules():
    with pytest.raises(ValueError, match="distinct"):
        canonical_roster({"anchor_groups": {"g:model.x": ["model.a"],
                                            "s:model.x": ["model.b"]}, "dense_targets": []})


@pytest.mark.parametrize("condition", ["absent", "claimed", "forked", "late", "errors"])
def test_worker_cannot_claim_incomplete_or_inherited_bootstrap(monkeypatch, condition):
    recorder = SimpleNamespace(process_id=os.getpid(), _early=True, _errors=[])
    if condition == "forked":
        recorder.process_id += 1
    if condition == "late":
        recorder._early = False
    if condition == "errors":
        recorder._errors.append("fixture history failed")
    monkeypatch.setattr(bootstrap, "_recorder", None if condition == "absent" else recorder)
    monkeypatch.setattr(bootstrap, "_claimed", condition == "claimed")
    with pytest.raises(RuntimeError):
        bootstrap.claim()


def test_worker_claim_is_unique(monkeypatch):
    recorder = SimpleNamespace(process_id=os.getpid(), _early=True, _errors=[])
    plan = {"identity": "fixture"}
    monkeypatch.setattr(bootstrap, "_recorder", recorder)
    monkeypatch.setattr(bootstrap, "_plan", plan)
    monkeypatch.setattr(bootstrap, "_claimed", False)
    assert bootstrap.claim() == (recorder, plan)
    with pytest.raises(RuntimeError):
        bootstrap.claim()


def test_late_bootstrap_fails_before_loading_collector(monkeypatch):
    monkeypatch.setattr(bootstrap, "_recorder", None)
    monkeypatch.setenv("TESSERA_ENGINE_RESOURCE_PLAN", "/unused.json")
    monkeypatch.setitem(sys.modules, "vllm", SimpleNamespace())
    with pytest.raises(RuntimeError, match="precede"):
        bootstrap.start()


@pytest.fixture
def worker_module(monkeypatch):
    class StockWorker:
        def __init__(self, *args, **kwargs):
            self.model_runner = None
        def init_device(self):
            return "device"
        def execute_model(self, scheduler_output):
            return scheduler_output
        def sample_tokens(self, grammar_output):
            return grammar_output
        def initialize_from_config(self, kv_cache_config):
            return "kv initialized"
    monkeypatch.setitem(sys.modules, "vllm.v1.worker.gpu_worker", SimpleNamespace(Worker=StockWorker))
    sys.modules.pop("experiments.full_engine_worker", None)
    module = importlib.import_module("experiments.full_engine_worker")
    yield module
    sys.modules.pop("experiments.full_engine_worker", None)


def test_parameter_classification_keeps_router_and_tied_head_fixed(worker_module):
    classify = worker_module.parameter_category
    units = ["model.layers.2.feed_forward.experts", "model.layers.0.feed_forward.w13"]
    assert classify("model.layers.2.feed_forward.experts.w13_weight", units) == "candidate"
    assert classify("model.layers.2.feed_forward.gate.weight", units) == "fixed"
    assert classify("model.layers.2.feed_forward.experts.routed_experts.e_score_correction_bias", units) == "fixed"
    assert classify("model.layers.2.feed_forward.experts_extra.weight", units) == "fixed"
    assert classify("lm_head.weight", units) == "fixed"
    assert classify("model.embed_tokens.weight", units) == "fixed"


def test_native_observation_hashes_generated_bytes_and_retains_missing_paths(
        monkeypatch, worker_module, tmp_path):
    import hashlib
    from experiments import bench_native_operator
    binary = tmp_path / "cuda_utils.so"
    binary.write_bytes(b"distinct actual generated bytes")
    missing = tmp_path / "deleted.so"
    monkeypatch.setattr(bench_native_operator, "_mapped_shared_libraries", lambda: {binary, missing})
    result = worker_module.native_library_observation()
    assert result["libraries"][str(binary)]["sha256"] == hashlib.sha256(binary.read_bytes()).hexdigest()
    assert result["errors"][0]["path"] == str(missing)
    assert result["runtime_admission"] is False


def test_worker_bounds_execute_capture_but_preserves_stock_outputs(monkeypatch, worker_module):
    seen = []
    recorder = SimpleNamespace(snapshot=lambda label, **kwargs: seen.append(label))
    plan = {"max_execute_calls": 2}
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, plan))
    worker = worker_module.ResourceCaptureWorker()
    assert worker.init_device() == "device"
    worker.resource_capture_arm()
    for index in range(1, 4):
        step = SimpleNamespace(total_num_scheduled_tokens=index, num_scheduled_tokens={"fixture": index},
            scheduled_new_reqs=[], scheduled_cached_reqs=SimpleNamespace(req_ids=[], num_computed_tokens=[]))
        assert worker.execute_model(step) is step
        assert worker.sample_tokens(index) == index
    assert seen == ["device_initialized", "ready_for_workload", "execute:1:begin", "execute:1:end", "sample:1:end",
                    "execute:2:begin", "execute:2:end", "sample:2:end"]
    assert worker._resource_active is False
    assert len(worker._resource_scheduler_steps) == 2
    with pytest.raises(RuntimeError, match="already armed"):
        worker.resource_capture_arm()


def test_stock_warmup_cannot_consume_the_workload_capture_budget(monkeypatch, worker_module):
    seen = []
    recorder = SimpleNamespace(snapshot=lambda label, **kwargs: seen.append(label))
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, {"max_execute_calls": 2}))
    worker = worker_module.ResourceCaptureWorker()
    assert worker.execute_model("stock warmup") == "stock warmup"
    assert worker.sample_tokens("warmup sample") == "warmup sample"
    assert seen == []
    assert worker._resource_calls == 0


def test_failed_stock_execute_still_records_boundary_and_disarms(monkeypatch, worker_module):
    seen = []
    recorder = SimpleNamespace(snapshot=lambda label, **kwargs: seen.append(label))
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, {"max_execute_calls": 1}))
    def fail(*args):
        raise RuntimeError("stock fixture failed")
    monkeypatch.setattr(worker_module.Worker, "execute_model", fail)
    worker = worker_module.ResourceCaptureWorker()
    worker.resource_capture_arm()
    step = SimpleNamespace(total_num_scheduled_tokens=1, num_scheduled_tokens={"fixture": 1},
        scheduled_new_reqs=[], scheduled_cached_reqs=SimpleNamespace(req_ids=[], num_computed_tokens=[]))
    with pytest.raises(RuntimeError, match="stock fixture"):
        worker.execute_model(step)
    assert seen == ["ready_for_workload", "execute:1:begin", "execute:1:end"]
    assert worker._resource_active is False


def test_worker_preserves_stock_1970_kv_placement_descriptors(monkeypatch, worker_module):
    seen = []
    recorder = SimpleNamespace(snapshot=lambda label, **kwargs: seen.append(label))
    monkeypatch.setattr(worker_module, "claim", lambda: (recorder, {}))
    worker = worker_module.ResourceCaptureWorker()
    tensor = SimpleNamespace(size=8192, layers=["attention", "recurrent"],
                             layer_stride=512, block_stride=1024, offset=128)
    config = SimpleNamespace(num_blocks=8, kv_cache_tensors=[tensor])
    assert worker.initialize_from_config(config) == "kv initialized"
    assert worker._resource_kv_description["tensors"] == [{
        "size": 8192, "layers": ["attention", "recurrent"],
        "layer_stride": 512, "block_stride": 1024, "offset": 128}]
    assert seen == ["before_kv_allocation", "kv_allocated"]


def test_resolved_kv_description_preserves_group_types_and_capacity_policy(worker_module):
    from dataclasses import dataclass
    import torch

    @dataclass
    class RecurrentSpec:
        block_size: int
        shapes: tuple
        dtypes: tuple
        page_size_padded: int

        @property
        def page_size_bytes(self):
            return self.page_size_padded

    @dataclass
    class Group:
        layer_names: list
        kv_cache_spec: object
        is_eagle_group: bool = False
        enable_kv_transfer: bool = True

    @dataclass
    class Config:
        num_blocks: int
        kv_cache_tensors: list
        kv_cache_groups: list
        prefix_cache_retention_interval: int = 64
        kv_cache_layout: str = "block_layer"

    config = Config(8, [], [Group(["conv"], RecurrentSpec(64, ((2, 4),), (torch.bfloat16,), 1024))])
    cache = SimpleNamespace(gpu_memory_utilization=0.35, kv_cache_memory_bytes=8192,
                            num_gpu_blocks_override=None)
    worker = SimpleNamespace(vllm_config=SimpleNamespace(cache_config=cache),
                             model_runner=SimpleNamespace(kv_cache_config=config, kernel_block_sizes=[64]))
    result = worker_module.kv_configuration_observation(worker, config)
    assert result["capacity_policy"]["values"]["kv_cache_memory_bytes"] == 8192
    assert "block_size" in result["capacity_policy"]["missing_fields"]
    resolved = result["runner_resolved"]
    assert resolved["fields"]["num_blocks"] == 8
    group = resolved["fields"]["kv_cache_groups"][0]
    spec = group["fields"]["kv_cache_spec"]
    assert spec["type"].endswith("RecurrentSpec")
    assert spec["fields"]["dtypes"] == [{"torch_dtype": "torch.bfloat16"}]
    assert result["group_page_size_bytes"] == [1024]
    assert result["physical_backing_bytes"] is None
    assert result["runtime_admission"] is False


def test_kv_config_serialization_refuses_unrecordable_values(worker_module):
    with pytest.raises(TypeError, match="unsupported"):
        worker_module.kv_config_value(object())
