"""Trim the GLM-5.3 BAL TP2 MTP draft census receipt r5 into a replay fixture.

Source run ``u4-BAL-20260928T0540Z-2c-r5`` (2026-09-28, GLM-5.3 PACT BAL, TP2
on two GB10s, vLLM eager, ``--speculative-config`` MTP with
``num_speculative_tokens=1``, ``max_num_seqs=1``, 64 prompt tokens).  That
receipt was REFUSED on 533 problems, all from one cause: the census asked the
generation phase for the one-row decode regime, which a k=1 draft never runs.

The fixture keeps one body module for each distinct served
``(policy, kind, decoder, symbol)`` on rank 0 (the same names on both ranks,
both phases), the MTP expert stack, every forward-observer row verbatim, the
checkpoint's ``config_groups`` for exactly those targets, and the problems the
original receipt recorded for them.  It is copied bytes, not a new measurement.

Usage (reads two named files; writes the fixture)::

    python3 tests/fixtures/generate_route_census_mtp_r5.py \
        --receipt <2c-evidence>/draft-route-census.json \
        --config <exported>/config.json \
        --out tests/fixtures/route_census_mtp_k1_r5.json
"""
import argparse
import hashlib
import json
from pathlib import Path

RUN = "u4-BAL-20260928T0540Z-2c-r5"


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--receipt", type=Path, required=True)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    raw = args.receipt.read_bytes()
    receipt = json.loads(raw)
    config = json.loads(args.config.read_text())

    rank0 = receipt["ranks"][0]["records"]
    phases = sorted(rank0)
    chosen = {}
    for name, record in sorted(rank0[phases[0]].items()):
        key = (record["policy"], record["kind"], record["decoder"], record["symbol"])
        chosen.setdefault(key, name)
    modules = sorted(chosen.values())
    owners = {name: receipt["record_owner"][phases[0]][name] for name in modules}
    module_to_source = {module: source
                        for source, module in receipt["declared_name_mapping"].items()}
    body_sources = sorted(module_to_source[owners[name]] for name in modules)
    draft = receipt["draft"]
    draft_sources = sorted(draft["source_declarations"])
    wanted = set(body_sources) | set(draft_sources)
    groups = {key: group for key, group in config["quantization_config"]["config_groups"].items()
              if set(group.get("targets", ())) & wanted}
    assert {t for g in groups.values() for t in g["targets"]} == wanted

    def qualified(rank, name):
        return f"rank{rank}/{name}"

    kept = {qualified(rank, name) for rank in range(len(receipt["ranks"])) for name in modules}
    original_problems = [
        problem for problem in receipt["problems"]
        if problem.startswith("draft")
        or any(f"{name}:" in problem or f"{name} " in problem for name in kept)]

    fixture = {
        "note": ("Trimmed from the served MTP draft route census of run " + RUN + " "
                 "(GLM-5.3 PACT BAL, TP2 GB10, eager, MTP num_speculative_tokens=1). "
                 "Generated by tests/fixtures/generate_route_census_mtp_r5.py; copied "
                 "bytes, not a new measurement."),
        "source": {"run": RUN, "receipt_sha256": hashlib.sha256(raw).hexdigest(),
                   "verdict": receipt["verdict"], "problem_count": len(receipt["problems"])},
        "config": {
            "model_type": config["model_type"], "architectures": config["architectures"],
            "text_config": {k: config["text_config"][k]
                            for k in ("num_hidden_layers", "num_nextn_predict_layers")},
            "quantization_config": {"config_groups": groups},
        },
        "prompt_tokens": receipt["prompt_tokens"],
        "runtime": receipt["runtime"],
        "platform": receipt["device"]["platform_token"],
        "serve_mode": receipt["env"]["TESSERA_SERVE_MODE"],
        "declared_name_mapping": {source: receipt["declared_name_mapping"][source]
                                  for source in body_sources},
        "ranks": [
            {"identity": {k: rank[k] for k in ("rank", "local_rank", "world_size", "node",
                                               "device", "platform_token", "runtime_image")},
             "lane_refusals": rank["lane_refusals"],
             "records": {phase: {name: rank["records"][phase][name] for name in modules}
                         for phase in phases}}
            for rank in receipt["ranks"]],
        "draft": {"speculative_config": draft["speculative_config"],
                  "source_to_module": draft["source_to_module"],
                  "requested_batch_prompts": draft["requested_batch_prompts"],
                  "arms": draft["forward_observer"]["arms"]},
        "original_problems_for_kept_modules": original_problems,
    }
    args.out.write_text(json.dumps(fixture, indent=1, sort_keys=True) + "\n")


if __name__ == "__main__":
    main()
